"use client";

import {Download,Grid3X3,Maximize2,Rotate3D,X} from "lucide-react";
import {useEffect,useMemo,useRef,useState} from "react";

type Side="front"|"back";
type Design={enabled:boolean;template:string;title:string;subtitle:string;detail:string;ink:string;accent:string;font:string;position:string;scale:number;logo:string|null};
type Project={fit:string;shirt:string;activeSide:Side;sides:Record<Side,Design>};

const styles:Record<string,string>={weekend:"arch",afterhours:"stack",ordinary:"minimal",running:"sport",bloom:"serif",good:"badge"};
const family=(design:Design)=>design.font==="serif"?"Georgia, serif":design.font==="sans"?"Arial, sans-serif":"Arial Narrow, Impact, sans-serif";
function fitText(ctx:CanvasRenderingContext2D,text:string,y:number,size:number,maxWidth:number,font:string,weight=800){ctx.font=`${weight} ${size}px ${font}`;const measured=ctx.measureText(text).width;if(measured>maxWidth)ctx.font=`${weight} ${size*maxWidth/measured}px ${font}`;ctx.fillText(text,0,y)}
function renderArtwork(canvas:HTMLCanvasElement,design:Design,logo?:HTMLImageElement){canvas.width=2400;canvas.height=3000;const ctx=canvas.getContext("2d")!;ctx.clearRect(0,0,canvas.width,canvas.height);if(!design.enabled)return;ctx.save();ctx.translate(1200,1500);ctx.scale(4,4);ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle=design.ink;const font=family(design),style=styles[design.template]||"arch";
 if(style==="arch"){ctx.strokeStyle=design.ink;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-40,188,Math.PI*1.06,Math.PI*1.94);ctx.stroke();fitText(ctx,design.title,-95,103,530,font);fitText(ctx,design.subtitle,10,110,490,font);ctx.fillStyle=design.accent;ctx.fillRect(-165,83,330,8);ctx.fillStyle=design.ink;fitText(ctx,design.detail,142,20,470,"Arial",600)}
 if(style==="stack"){ctx.fillStyle=design.accent;ctx.save();ctx.rotate(-.06);ctx.fillRect(-246,-183,492,122);ctx.restore();ctx.fillStyle=design.ink;fitText(ctx,design.title,-127,126,470,font);fitText(ctx,design.subtitle,0,136,520,font);fitText(ctx,design.detail,127,21,475,"Arial",600);ctx.fillRect(-215,79,430,3)}
 if(style==="minimal"){fitText(ctx,design.title,-50,98,510,design.font==="condensed"?"Georgia":font,400);ctx.fillRect(-27,36,54,3);fitText(ctx,design.subtitle,95,23,470,"Arial",600);fitText(ctx,design.detail,142,17,440,"Arial",400)}
 if(style==="sport"){ctx.strokeStyle=design.ink;ctx.lineWidth=5;ctx.strokeRect(-244,-193,488,370);ctx.save();ctx.transform(1,0,-.14,1,0,0);fitText(ctx,design.title,-102,112,420,font);fitText(ctx,design.subtitle,0,94,420,font);ctx.restore();ctx.fillStyle=design.accent;ctx.fillRect(-244,76,488,101);ctx.fillStyle=design.ink;fitText(ctx,design.detail,127,20,447,"Arial",700)}
 if(style==="serif"){ctx.strokeStyle=design.accent;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,-26,236,193,-.2,0,Math.PI*2);ctx.stroke();fitText(ctx,design.title,-55,107,510,design.font==="condensed"?"Georgia":font,600);fitText(ctx,design.subtitle,63,24,460,"Arial",600);fitText(ctx,design.detail,203,19,450,"Arial",400)}
 if(style==="badge"){ctx.fillStyle=design.accent;ctx.beginPath();ctx.arc(0,-25,215,0,Math.PI*2);ctx.fill();ctx.fillStyle=design.ink;fitText(ctx,design.title,-74,139,430,font);fitText(ctx,design.subtitle,37,41,415,font);ctx.fillRect(-110,90,220,3);fitText(ctx,design.detail,137,15,340,"Arial",600)}
 if(logo){const ratio=logo.width/logo.height,w=Math.min(170,110*ratio),h=w/ratio;ctx.drawImage(logo,-w/2,235,w,h)}ctx.restore()}

function downloadCanvas(canvas:HTMLCanvasElement|null,name:string){if(!canvas)return;canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),30000)},"image/png")}

export default function PartnerDesignView({production,onClose}:{production:any;onClose:()=>void}){
 const item=production.order.items[0],designRecord=item?.storeProduct?.design,project=designRecord?.canvas as Project|undefined;
 const [side,setSide]=useState<Side>("front"),[view,setView]=useState<"artwork"|"product">("artwork"),[grid,setGrid]=useState(true),[perspective,setPerspective]=useState(false),[zoom,setZoom]=useState(75),canvas=useRef<HTMLCanvasElement>(null),[logo,setLogo]=useState<HTMLImageElement>();
 const active=project?.sides?.[side];
 useEffect(()=>{if(!active?.logo){setLogo(undefined);return}const image=new Image();image.onload=()=>setLogo(image);image.src=active.logo},[active?.logo]);
 useEffect(()=>{if(canvas.current&&active)renderArtwork(canvas.current,active,logo)},[active,logo]);
 const slug=useMemo(()=>String(designRecord?.name||"design").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),[designRecord?.name]);
 if(!project||!active)return <div className="tech-backdrop"><div className="tech-viewer tech-empty"><button onClick={onClose}><X/></button><h2>Data desain tidak tersedia</h2><p>Order ini tidak memiliki canvas desain yang dapat ditampilkan.</p></div></div>;
 return <div className="tech-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="tech-viewer">
  <header><div><span>PRODUCTION DESIGN INSPECTOR</span><h2>{designRecord.name}</h2></div><button className="tech-close" onClick={onClose} aria-label="Tutup"><X size={20}/></button></header>
  <div className="tech-body"><aside className="tech-meta"><div className="tech-section"><span>ORDER</span><strong>{production.order.orderNumber}</strong><dl><dt>Customer</dt><dd>{production.order.customer.name}</dd><dt>Produk</dt><dd>{item.product.name}</dd><dt>Varian</dt><dd>{item.variantName||"—"}</dd><dt>Jumlah</dt><dd>{item.quantity} pcs</dd><dt>Area cetak</dt><dd>{item.product.printArea}</dd><dt>Status</dt><dd>{production.status}</dd></dl></div><div className="tech-section"><span>FILE CHECK</span><ul><li className={active.enabled?"ok":"warn"}>{active.enabled?"Artwork tersedia":"Sisi kosong"}</li><li className="ok">Canvas 2400 × 3000 px</li><li className={active.logo?"ok":"neutral"}>{active.logo?"Logo raster terpasang":"Tanpa logo tambahan"}</li><li className="ok">Background transparan</li></ul></div><div className="tech-note"><b>Alamat kirim</b><p>{production.order.shippingAddress}</p></div></aside>
   <main className={`tech-canvas-area${grid&&view==="artwork"?" show-grid":""}`}><div className="tech-toolbar"><div className="tech-view-tabs"><button className={view==="artwork"?"active":""} onClick={()=>setView("artwork")}>Artwork</button><button className={view==="product"?"active":""} onClick={()=>setView("product")}>Preview Product</button>{view==="artwork"&&<><button className={side==="front"?"active":""} onClick={()=>setSide("front")}>Depan</button><button className={side==="back"?"active":""} onClick={()=>setSide("back")}>Belakang</button></>}</div><div><button className={grid?"active":""} onClick={()=>setGrid(value=>!value)} title="Grid dan ruler" disabled={view==="product"}><Grid3X3 size={16}/></button><button className={perspective?"active":""} onClick={()=>setPerspective(value=>!value)} title="Perspective view"><Rotate3D size={17}/></button><button onClick={()=>setZoom(100)} title="Ukuran 100%"><Maximize2 size={16}/></button></div></div><div className="tech-workbench"><div className="tech-ruler-x"><i>0</i><i>5</i><i>10</i><i>15</i><i>20</i><i>25</i></div><div className="tech-ruler-y"><i>0</i><i>5</i><i>10</i><i>15</i><i>20</i><i>25</i><i>30</i></div><div className={`tech-sheet${perspective?" perspective":""}${view==="product"?" product-mode":""}`} style={{width:`${zoom}%`}}>{view==="artwork"?<><canvas ref={canvas}/><div className="tech-safe-area">SAFE AREA</div></>:designRecord.preview?<img className="tech-product-preview" src={designRecord.preview} alt={`Preview produk ${designRecord.name}`}/>:<div className="tech-no-preview">Preview produk belum tersedia</div>}</div></div><div className="tech-zoom"><span>25%</span><input type="range" min="25" max="100" value={zoom} onChange={event=>setZoom(Number(event.target.value))}/><span>{zoom}%</span></div></main>
   <aside className="tech-export"><div className="tech-section"><span>EXPORT PRODUKSI</span><h3>File siap cetak</h3><p>Artwork transparan berukuran 2400 × 3000 px untuk sisi {side==="front"?"depan":"belakang"}.</p><button className="tech-download" disabled={!active.enabled} onClick={()=>downloadCanvas(canvas.current,`${slug}-${side}-print.png`)}><Download size={16}/> Export artwork PNG</button>{designRecord.preview&&<button onClick={()=>{const anchor=document.createElement("a");anchor.href=designRecord.preview;anchor.download=`${slug}-mockup.png`;anchor.click()}}><Download size={16}/> Export mockup</button>}</div><div className="tech-warning"><b>Preflight reminder</b><p>Periksa resolusi logo, posisi safe area, warna bahan, dan ukuran cetak aktual sebelum produksi.</p></div></aside>
  </div>
 </section></div>
}
