"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Download,Redo2,RotateCcw,Save,ShoppingCart,Undo2,X} from "lucide-react";
import {useRouter,useSearchParams} from "next/navigation";

type Product={id:string;name:string;image:string;basePrice:number;printArea:string;category?:string;variants?:{id:string;name:string;color:string;size:string;stock?:number}[]};
type Side="front"|"back";
type Design={enabled:boolean;template:string;title:string;subtitle:string;detail:string;ink:string;accent:string;font:"condensed"|"sans"|"serif";position:"chest"|"center"|"large";scale:number;logo:string|null};
type Project={fit:"regular"|"oversized";shirt:string;activeSide:Side;sides:Record<Side,Design>};

const templates=[
 {id:"weekend",name:"Weekend Society",category:"Komunitas",title:"WEEKEND",subtitle:"SOCIETY",detail:"GOOD PEOPLE. GREAT DAYS.",style:"arch",bg:"#e4ead9",ink:"#294f36",accent:"#b1cf6d"},
 {id:"afterhours",name:"After Hours",category:"Event",title:"AFTER",subtitle:"HOURS",detail:"MUSIC • PEOPLE • MEMORIES",style:"stack",bg:"#dddcef",ink:"#39216b",accent:"#fa724a"},
 {id:"ordinary",name:"Less, But Better",category:"Brand",title:"ordinary.",subtitle:"STUFF WITH SOUL",detail:"EST. 2026 / JAKARTA",style:"minimal",bg:"#ece5db",ink:"#342f2a",accent:"#bd744e"},
 {id:"running",name:"Sunday Run Club",category:"Komunitas",title:"SUNDAY",subtitle:"RUN CLUB",detail:"YOUR PACE. YOUR PEOPLE.",style:"sport",bg:"#e6ecc7",ink:"#293829",accent:"#81a82c"},
 {id:"bloom",name:"In My Own Time",category:"Personal",title:"BLOOM",subtitle:"IN YOUR OWN TIME",detail:"NO RUSH. JUST GROW.",style:"serif",bg:"#f0deda",ink:"#913e41",accent:"#ed9584"},
 {id:"good",name:"Good Things Ahead",category:"Personal",title:"GOOD",subtitle:"THINGS AHEAD",detail:"TAKE IT ONE DAY AT A TIME",style:"badge",bg:"#dce8ee",ink:"#1c5068",accent:"#e9a640"}
] as const;
const palettes=[["#294f36","#b1cf6d"],["#242424","#f4eee1"],["#39216b","#fa724a"],["#913e41","#ed9584"],["#f4eee1","#c6f34b"]];
const shirts=[["#f5f3ea","Putih tulang"],["#27292a","Hitam"],["#a5af8e","Sage"],["#aab9ca","Biru"],["#eee0c9","Sand"]];
const baseDesign:Design={enabled:true,template:"weekend",title:"WEEKEND",subtitle:"SOCIETY",detail:"GOOD PEOPLE. GREAT DAYS.",ink:"#294f36",accent:"#b1cf6d",font:"condensed",position:"center",scale:100,logo:null};
const initialProject:Project={fit:"oversized",shirt:"#f4f1eb",activeSide:"front",sides:{front:{...baseDesign},back:{...baseDesign,enabled:false,position:"large"}}};
const clone=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const fontFamily=(s:Design)=>s.font==="serif"?"Georgia, serif":s.font==="sans"?"Arial, sans-serif":"Arial Narrow, Impact, sans-serif";

function fitText(ctx:CanvasRenderingContext2D,text:string,y:number,size:number,maxWidth:number,family:string,weight=800){ctx.font=`${weight} ${size}px ${family}`;const measured=ctx.measureText(text).width;if(measured>maxWidth)ctx.font=`${weight} ${size*maxWidth/measured}px ${family}`;ctx.fillText(text,0,y)}
function drawDesign(ctx:CanvasRenderingContext2D,s:Design,width:number,height:number,logo?:HTMLImageElement){if(!s.enabled)return;const t=templates.find(x=>x.id===s.template)||templates[0];ctx.save();ctx.translate(width/2,height/2);const factor=Math.min(width/600,height/750);ctx.scale(factor,factor);ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle=s.ink;const family=fontFamily(s);
 if(t.style==="arch"){ctx.strokeStyle=s.ink;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-40,188,Math.PI*1.06,Math.PI*1.94);ctx.stroke();fitText(ctx,s.title,-95,103,530,family);fitText(ctx,s.subtitle,10,110,490,family);ctx.fillStyle=s.accent;ctx.fillRect(-165,83,330,8);ctx.fillStyle=s.ink;fitText(ctx,s.detail,142,20,470,"Arial",600)}
 if(t.style==="stack"){ctx.fillStyle=s.accent;ctx.save();ctx.rotate(-.06);ctx.fillRect(-246,-183,492,122);ctx.restore();ctx.fillStyle=s.ink;fitText(ctx,s.title,-127,126,470,family);fitText(ctx,s.subtitle,0,136,520,family);fitText(ctx,s.detail,127,21,475,"Arial",600);ctx.fillRect(-215,79,430,3)}
 if(t.style==="minimal"){fitText(ctx,s.title,-50,98,510,s.font==="condensed"?"Georgia":family,400);ctx.fillRect(-27,36,54,3);fitText(ctx,s.subtitle,95,23,470,"Arial",600);fitText(ctx,s.detail,142,17,440,"Arial",400)}
 if(t.style==="sport"){ctx.strokeStyle=s.ink;ctx.lineWidth=5;ctx.strokeRect(-244,-193,488,370);ctx.save();ctx.transform(1,0,-.14,1,0,0);fitText(ctx,s.title,-102,112,420,family);fitText(ctx,s.subtitle,0,94,420,family);ctx.restore();ctx.fillStyle=s.accent;ctx.fillRect(-244,76,488,101);ctx.fillStyle=s.ink;fitText(ctx,s.detail,127,20,447,"Arial",700)}
 if(t.style==="serif"){ctx.strokeStyle=s.accent;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,-26,236,193,-.2,0,Math.PI*2);ctx.stroke();fitText(ctx,s.title,-55,107,510,s.font==="condensed"?"Georgia":family,600);fitText(ctx,s.subtitle,63,24,460,"Arial",600);fitText(ctx,s.detail,203,19,450,"Arial",400)}
 if(t.style==="badge"){ctx.fillStyle=s.accent;ctx.beginPath();ctx.arc(0,-25,215,0,Math.PI*2);ctx.fill();ctx.fillStyle=s.ink;fitText(ctx,s.title,-74,139,430,family);fitText(ctx,s.subtitle,37,41,415,family);ctx.fillRect(-110,90,220,3);fitText(ctx,s.detail,137,15,340,"Arial",600)}
 if(logo){const ratio=logo.width/logo.height;const w=Math.min(170,110*ratio),h=w/ratio;ctx.drawImage(logo,-w/2,235,w,h)}ctx.restore()}

function TemplateCard({template,active,onClick}:{template:typeof templates[number];active:boolean;onClick:()=>void}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;ctx.fillStyle=template.bg;ctx.fillRect(0,0,c.width,c.height);drawDesign(ctx,{...baseDesign,...template,font:"condensed",logo:null},c.width,c.height)},[template]);return <button className={`ms-template${active?" active":""}`} onClick={onClick}><canvas ref={ref} width="280" height="312"/><strong>{template.name}</strong><small>{template.category}</small></button>}

export default function Studio({products,user,onLogin}:{products:Product[];user:any;onLogin:()=>void}){
 const search=useSearchParams(),router=useRouter();
 const canvasRef=useRef<HTMLCanvasElement>(null),shirtImages=useRef<Partial<Record<Side,HTMLImageElement>>>({}),logoImages=useRef(new Map<string,HTMLImageElement>()),history=useRef<Project[]>([]),future=useRef<Project[]>([]);
 const [project,setProject]=useState<Project>(initialProject),[designName,setDesignName]=useState("Desain tanpa judul"),[category,setCategory]=useState("Semua"),[toast,setToast]=useState(""),[dirty,setDirty]=useState(false),[savedId,setSavedId]=useState(""),[busy,setBusy]=useState(false),[downloadOpen,setDownloadOpen]=useState(false),[orderOpen,setOrderOpen]=useState(false),[orderQty,setOrderQty]=useState(1),[orderAddress,setOrderAddress]=useState(""),[variantId,setVariantId]=useState(""),[exportSide,setExportSide]=useState<Side>("front"),[ready,setReady]=useState(false),[,forceHistory]=useState(0);
 const product=products.find(item=>item.id===search.get("product"))||products.find(item=>item.name.toLowerCase().includes("t-shirt"))||products[0],state=project.sides[project.activeSide];
 const productColors=useMemo(()=>{const values=product?.variants?.map(v=>[v.color,v.name.split("/").pop()?.trim()||v.name] as [string,string])||[];return values.filter((entry,index)=>values.findIndex(value=>value[0]===entry[0])===index)},[product]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2800)};
 const mutate=useCallback((change:(next:Project)=>void)=>{setProject(current=>{history.current.push(clone(current));if(history.current.length>50)history.current.shift();future.current=[];const next=clone(current);change(next);return next});setDirty(true);forceHistory(v=>v+1)},[]);
 const designCanvas=useCallback((design:Design)=>{const c=document.createElement("canvas");c.width=2400;c.height=3000;drawDesign(c.getContext("2d")!,design,c.width,c.height,design.logo?logoImages.current.get(design.logo):undefined);return c},[]);
 const mockupCanvas=useCallback((side:Side,background=false)=>{if(!product)return null;const c=document.createElement("canvas");c.width=1000;c.height=1100;const ctx=c.getContext("2d")!;if(background){ctx.fillStyle="#f1f2ee";ctx.fillRect(0,0,1000,1100)}const kind=product.name.toLowerCase(),regular=project.fit==="regular";let dx=500,dy=440,dw=regular?285:330;
  if(kind.includes("t-shirt")){const photo=shirtImages.current[side],mask=shirtImages.current.front;if(!photo||!mask)return null;const w=regular?790:930,h=930,x=(1000-w)/2,y=40,garment=document.createElement("canvas");garment.width=1000;garment.height=1100;const g=garment.getContext("2d")!;g.drawImage(mask,x,y,w,h);g.globalCompositeOperation="source-in";g.fillStyle=project.shirt;g.fillRect(0,0,1000,1100);g.globalCompositeOperation="multiply";g.drawImage(photo,x,y,w,h);g.globalCompositeOperation="destination-in";g.drawImage(mask,x,y,w,h);ctx.save();ctx.shadowColor="#1b271820";ctx.shadowBlur=28;ctx.shadowOffsetY=20;ctx.drawImage(garment,0,0);ctx.restore()}
  else{ctx.save();ctx.shadowColor="#1b27182a";ctx.shadowBlur=34;ctx.shadowOffsetY=22;ctx.fillStyle=project.shirt;ctx.strokeStyle="#1d271c2b";ctx.lineWidth=7;if(kind.includes("hoodie")){ctx.beginPath();ctx.roundRect(245,245,510,690,70);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(330,300);ctx.quadraticCurveTo(500,45,670,300);ctx.quadraticCurveTo(585,390,500,390);ctx.quadraticCurveTo(415,390,330,300);ctx.fill();ctx.stroke();ctx.beginPath();ctx.roundRect(338,720,324,145,30);ctx.stroke();dy=540;dw=310}else if(kind.includes("tote")){ctx.beginPath();ctx.roundRect(255,310,490,610,32);ctx.fill();ctx.stroke();ctx.lineWidth=28;ctx.beginPath();ctx.arc(500,340,145,Math.PI,0);ctx.stroke();dy=570;dw=315}else if(kind.includes("mug")){ctx.beginPath();ctx.roundRect(230,320,470,520,72);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(710,565,145,-Math.PI/2,Math.PI/2);ctx.lineWidth=55;ctx.stroke();ctx.fillStyle="#ffffff55";ctx.beginPath();ctx.ellipse(465,335,225,45,0,0,Math.PI*2);ctx.fill();dy=575;dw=280}else{ctx.beginPath();ctx.roundRect(280,160,440,780,30);ctx.fill();ctx.stroke();ctx.fillStyle="#ffffff24";ctx.fillRect(305,185,18,730);ctx.strokeStyle="#ffffff55";ctx.lineWidth=2;for(let y=220;y<900;y+=36){ctx.beginPath();ctx.moveTo(350,y);ctx.lineTo(680,y);ctx.stroke()}dy=535;dw=265}ctx.restore()}
  const design=project.sides[side];if(design.enabled){const factor=design.scale/100;if(design.position==="chest"){dw*=.45;dx=kind.includes("t-shirt")&&side==="front"?610:500;dy=kind.includes("notebook")?350:360}if(design.position==="large")dw*=1.25;dw*=factor;const dh=dw*1.25;ctx.drawImage(designCanvas(design),dx-dw/2,dy-dh/2,dw,dh)}return c},[project,product,designCanvas]);
 const renderPreview=useCallback(()=>{const target=canvasRef.current;if(!target)return;const ctx=target.getContext("2d")!;ctx.clearRect(0,0,target.width,target.height);const mockup=mockupCanvas(project.activeSide);if(mockup)ctx.drawImage(mockup,0,0)},[mockupCanvas,project.activeSide]);
 useEffect(()=>{let mounted=true;Promise.all((["front","back"] as Side[]).map(side=>new Promise<void>((resolve,reject)=>{const img=new Image();img.onload=()=>{shirtImages.current[side]=img;resolve()};img.onerror=reject;img.src=side==="front"?"/studio/shirt.png":"/studio/shirt-back.png"}))).then(()=>{if(mounted){setReady(true);renderPreview()}}).catch(()=>notify("Mockup gagal dimuat. Muat ulang halaman."));return()=>{mounted=false}},[renderPreview]);
 useEffect(()=>{renderPreview()},[renderPreview,ready]);
 useEffect(()=>{if(!search.get("design"))setSavedId("")},[product?.id,search]);
 useEffect(()=>{const id=search.get("design");if(!id||!user)return;let active=true;setBusy(true);fetch(`/api/designs?id=${encodeURIComponent(id)}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Desain gagal dibuka.");if(!active)return;const next=data.canvas as Project;if(!next?.sides?.front||!next?.sides?.back)throw new Error("Format desain tidak didukung.");for(const side of ["front","back"] as Side[]){const logo=next.sides[side].logo;if(logo&&!logoImages.current.has(logo)){const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=reject;value.src=logo});logoImages.current.set(logo,image)}}setProject(next);setDesignName(data.name);setSavedId(data.id);setDirty(false);history.current=[];future.current=[];if(data.productId!==search.get("product"))router.replace(`/studio?product=${data.productId}&design=${data.id}`,{scroll:false})}).catch(error=>active&&notify(error instanceof Error?error.message:"Desain gagal dibuka.")).finally(()=>active&&setBusy(false));return()=>{active=false}},[search,user,router]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 function chooseTemplate(id:string){const t=templates.find(x=>x.id===id);if(!t)return;mutate(next=>Object.assign(next.sides[next.activeSide],{enabled:true,template:t.id,title:t.title,subtitle:t.subtitle,detail:t.detail,ink:t.ink,accent:t.accent}));notify(`Template diterapkan ke sisi ${project.activeSide==="front"?"depan":"belakang"}.`)}
 function undo(){const previous=history.current.pop();if(!previous)return;future.current.push(clone(project));setProject(previous);setDirty(true);forceHistory(v=>v+1)}
 function redo(){const next=future.current.pop();if(!next)return;history.current.push(clone(project));setProject(next);setDirty(true);forceHistory(v=>v+1)}
 async function uploadLogo(file?:File){if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>4*1024*1024){notify("Pilih PNG, JPG, atau WebP maksimal 4 MB.");return}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=reject;value.src=data});logoImages.current.set(data,img);mutate(next=>{next.sides[next.activeSide].logo=data});notify("Gambar ditambahkan ke desain.")}catch{notify("Gambar gagal dibuka.")}}
 async function save():Promise<string|null>{if(!user){onLogin();return null}if(user.role!=="CREATOR"){notify("Masuk dengan akun Creator untuk menyimpan desain.");return null}if(!product){notify("Produk belum tersedia.");return null}if(!designName.trim()){notify("Nama desain wajib diisi.");return null}const preview=mockupCanvas("front",true)?.toDataURL("image/png",.75);setBusy(true);try{const response=await fetch("/api/designs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:savedId||undefined,productId:product.id,name:designName,canvas:project,preview})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Desain gagal disimpan.");setSavedId(data.id);localStorage.setItem(`merch-studio-project-${product.id}`,JSON.stringify(project));setDirty(false);router.replace(`/studio?product=${product.id}&design=${data.id}`,{scroll:false});notify(`${designName} berhasil disimpan.`);return data.id}catch(error){notify(error instanceof Error?error.message:"Desain gagal disimpan.");return null}finally{setBusy(false)}}
 async function orderDesign(e:React.FormEvent){e.preventDefault();if(!product)return;const id=await save();if(!id)return;setBusy(true);try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({designId:id,variantId:variantId||product.variants?.[0]?.id,quantity:orderQty,shippingAddress:orderAddress})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Pesanan gagal dibuat.");setOrderOpen(false);notify("Pesanan masuk ke antrean produksi.");router.push("/orders")}catch(error){notify(error instanceof Error?error.message:"Pesanan gagal dibuat.")}finally{setBusy(false)}}
 async function openSaved(){if(!product)return;try{const raw=localStorage.getItem(`merch-studio-project-${product.id}`);if(!raw){notify(`Belum ada desain ${product.name} tersimpan di browser ini.`);return}const next=JSON.parse(raw) as Project;for(const side of ["front","back"] as Side[]){const logo=next.sides[side].logo;if(logo&&!logoImages.current.has(logo)){const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=reject;value.src=logo});logoImages.current.set(logo,img)}}history.current.push(clone(project));setProject(next);setDirty(false);notify(`Desain ${product.name} berhasil dibuka.`)}catch{notify("Desain tersimpan tidak bisa dibuka.")}}
 function download(canvas:HTMLCanvasElement|null,name:string){if(!canvas){notify("Mockup belum siap.");return}canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),30000)},"image/png")}
 function combined(){const front=mockupCanvas("front",true),back=mockupCanvas("back",true);if(!front||!back)return null;const c=document.createElement("canvas");c.width=2000;c.height=1100;const ctx=c.getContext("2d")!;ctx.drawImage(front,0,0);ctx.drawImage(back,1000,0);return c}
 const filtered=useMemo(()=>templates.filter(t=>category==="Semua"||t.category===category),[category]);

 return <div className="merch-studio-page">
  <main className="ms-main">
   <aside className="ms-sidebar"><div className="ms-eyebrow">MULAI DARI YANG LO SUKA</div><h1>Ide lo. Kaos lo.</h1><p className="ms-muted">Pilih desain, bikin jadi punya lo.</p>
    <section className="ms-product-picker"><div className="ms-eyebrow">01 / PRODUK</div><h2>Pilih merchandise</h2><div className="ms-product-list">{products.map(item=><button key={item.id} className={product?.id===item.id?"active":""} onClick={()=>{setDesignName(`Desain ${item.name}`);router.replace(`/studio?product=${item.id}`,{scroll:false})}}><img src={item.image} alt=""/><span><strong>{item.name}</strong><small>{item.category||"Merchandise"} · {new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(item.basePrice)}</small></span></button>)}</div></section>
    <section className="ms-garment"><div className="ms-eyebrow">02 / VARIAN</div><h2>{product?.name||"Produk"}</h2>{product?.name.toLowerCase().includes("t-shirt")&&<div className="ms-segmented">{(["regular","oversized"] as const).map(f=><button key={f} className={project.fit===f?"active":""} onClick={()=>mutate(n=>{n.fit=f})}>{f==="regular"?"Regular":"Oversized"}</button>)}</div>}<div className="ms-swatches">{(productColors.length?productColors:shirts).map(([color,label])=><button key={`${color}-${label}`} className={`ms-swatch${project.shirt===color?" active":""}`} style={{background:color}} aria-label={label} title={label} onClick={()=>mutate(n=>{n.shirt=color})}/>)}</div><div className="ms-color-label">Area cetak: {product?.printArea}</div><p className="ms-hint">Warna berlaku untuk sisi depan dan belakang.</p></section>
    <div className="ms-template-head"><div className="ms-eyebrow">03 / TEMPLATE DESAIN</div><h2>Pilih gaya lo</h2><p className="ms-hint">Untuk sisi {project.activeSide==="front"?"depan":"belakang"}</p></div><div className="ms-categories">{["Semua","Komunitas","Event","Brand","Personal"].map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="ms-templates">{filtered.map(t=><TemplateCard key={t.id} template={t} active={state.enabled&&state.template===t.id} onClick={()=>chooseTemplate(t.id)}/>)}</div><button className="ms-open" onClick={openSaved}><RotateCcw size={14}/> Buka versi browser</button><a className="ms-saved-link" href="/designs">Lihat semua desain tersimpan →</a>
   </aside>
   <section className="ms-workspace"><div className="ms-workspace-top"><input className="ms-design-name" value={designName} maxLength={80} aria-label="Nama desain" onChange={e=>{setDesignName(e.target.value);setDirty(true)}}/><div><button onClick={undo} disabled={!history.current.length} aria-label="Urungkan"><Undo2 size={18}/></button><button onClick={redo} disabled={!future.current.length} aria-label="Ulangi"><Redo2 size={18}/></button><button className="ms-toolbar-action" onClick={save} disabled={busy}><Save size={15}/>{busy?"Menyimpan…":"Simpan"}</button><button className="ms-toolbar-action" onClick={()=>{if(!user){onLogin();return}if(user.role!=="CREATOR"){notify("Pemesanan dari Studio khusus akun Creator.");return}setVariantId(product?.variants?.[0]?.id||"");setOrderOpen(true)}}><ShoppingCart size={15}/> Pesan</button><button className="ms-toolbar-action ms-primary" onClick={()=>{setExportSide(project.activeSide);setDownloadOpen(true)}}><Download size={15}/> Download</button></div></div><div className="ms-side-switch">{(["front","back"] as Side[]).map(side=><button key={side} className={project.activeSide===side?"active":""} onClick={()=>setProject(p=>({...p,activeSide:side}))}><strong>{side==="front"?"Depan":"Belakang"}</strong><small>{project.sides[side].enabled?"Ada desain":"Kosong"}</small></button>)}</div><div className="ms-preview"><canvas ref={canvasRef} width="1000" height="1100"/><span><b>{project.activeSide==="front"?"DEPAN":"BELAKANG"}</b> · MOCKUP</span></div><div className="ms-workspace-bottom"><span>✦ Desain bagus, nggak perlu ribet.</span><span>{dirty?"Ada perubahan":savedId?"Tersimpan di akun":"Belum disimpan"}</span></div></section>
   <section className="ms-controls"><div className="ms-eyebrow">BIKIN JADI PUNYA LO</div><h2>Desain {project.activeSide==="front"?"depan":"belakang"}</h2><button className="ms-clear" disabled={!state.enabled} onClick={()=>mutate(n=>{n.sides[n.activeSide].enabled=false})}>Kosongkan sisi ini</button>{state.enabled?<><div className="ms-control-group"><div className="ms-group-title"><span>2</span>Tulis cerita lo</div>{[["title","Tulisan utama",30],["subtitle","Tulisan kedua",40],["detail","Detail kecil",65]].map(([key,label,max])=><label className="ms-field" key={String(key)}><span>{label}</span><input maxLength={Number(max)} value={String(state[key as keyof Design])} onChange={e=>mutate(n=>{(n.sides[n.activeSide] as any)[key]=e.target.value})}/></label>)}<label className="ms-field"><span>Gaya huruf</span><select value={state.font} onChange={e=>mutate(n=>{n.sides[n.activeSide].font=e.target.value as Design["font"]})}><option value="condensed">Bold & compact</option><option value="sans">Clean & modern</option><option value="serif">Classic & editorial</option></select></label><label className="ms-field"><span>Warna desain</span></label><div className="ms-palettes">{palettes.map(([ink,accent])=><button key={ink} className={state.ink===ink?"active":""} onClick={()=>mutate(n=>{n.sides[n.activeSide].ink=ink;n.sides[n.activeSide].accent=accent})}><i style={{background:ink}}/><i style={{background:accent}}/></button>)}</div></div><div className="ms-control-group"><div className="ms-group-title"><span>3</span>Atur tampilannya</div><div className="ms-segmented">{(["chest","center","large"] as const).map(p=><button key={p} className={state.position===p?"active":""} onClick={()=>mutate(n=>{n.sides[n.activeSide].position=p})}>{p==="chest"?"Dada kecil":p==="center"?"Tengah":"Besar"}</button>)}</div><label className="ms-field"><span className="ms-size-label">Ukuran desain <output>{state.scale}%</output></span><input type="range" min="60" max="120" step="5" value={state.scale} onChange={e=>mutate(n=>{n.sides[n.activeSide].scale=Number(e.target.value)})}/></label><label className="ms-upload">＋ {state.logo?"Ganti gambar / logo":"Tambahkan gambar / logo"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadLogo(e.target.files?.[0])}/></label><p className="ms-hint">PNG, JPG, atau WebP · maks. 4 MB.<br/>PNG transparan cocok untuk logo.</p>{state.logo&&<button className="ms-remove" onClick={()=>mutate(n=>{n.sides[n.activeSide].logo=null})}>Hapus gambar</button>}</div></>:<div className="ms-empty"><span>＋</span><h3>Sisi ini masih kosong</h3><p>Pilih template desain di galeri untuk mulai. Model dan warna kaos lo tetap sama.</p></div>}</section>
  </main>
  <div className={`ms-toast${toast?" visible":""}`}>{toast}</div>
  {downloadOpen&&<div className="ms-dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDownloadOpen(false)}><div className="ms-dialog"><button className="ms-dialog-close" onClick={()=>setDownloadOpen(false)}><X size={18}/></button><div className="ms-eyebrow">PUNYA LO, SIAP DIBAWA</div><h2>Download desain</h2><p className="ms-muted">Download desain per sisi atau lihat satu kaos lengkap.</p><label className="ms-field"><span>Sisi yang diunduh</span><select value={exportSide} onChange={e=>setExportSide(e.target.value as Side)}><option value="front">Depan</option><option value="back">Belakang</option></select></label><button className="ms-download-option" disabled={!project.sides[exportSide].enabled} onClick={()=>download(designCanvas(project.sides[exportSide]),`bikinmerch-desain-${exportSide}.png`)}><strong>Desain transparan ↗</strong><small>PNG · 2400 × 3000 px · tanpa kaos</small></button><button className="ms-download-option" onClick={()=>download(mockupCanvas(exportSide,true),`bikinmerch-mockup-${exportSide}.png`)}><strong>Mockup kaos ↗</strong><small>PNG · 1000 × 1100 px · untuk preview</small></button><button className="ms-download-option" onClick={()=>download(combined(),"bikinmerch-mockup-depan-belakang.png")}><strong>Mockup depan + belakang ↗</strong><small>PNG · 2000 × 1100 px · dua sisi berdampingan</small></button><p className="ms-export-note">Untuk produksi, konfirmasi ukuran dan resolusi ke vendor cetak. Mockup hanya perkiraan tampilan.</p></div></div>}
  {orderOpen&&product&&<div className="ms-dialog-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOrderOpen(false)}><form className="ms-dialog" onSubmit={orderDesign}><button type="button" className="ms-dialog-close" onClick={()=>setOrderOpen(false)}><X size={18}/></button><div className="ms-eyebrow">PESAN HASIL DESAINMU</div><h2>Checkout produksi</h2><div className="ms-order-summary"><strong>{designName}</strong><span>{product.name}</span><b>{new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(product.basePrice*orderQty)}</b></div><label className="ms-field"><span>Varian produk</span><select required value={variantId} onChange={e=>setVariantId(e.target.value)}>{product.variants?.map(variant=><option key={variant.id} value={variant.id}>{variant.name} · stok {variant.stock??"tersedia"}</option>)}</select></label><label className="ms-field"><span>Jumlah</span><input required type="number" min="1" max="10" value={orderQty} onChange={e=>setOrderQty(Math.max(1,Math.min(10,Number(e.target.value)||1)))}/></label><label className="ms-field"><span>Alamat pengiriman</span><textarea required rows={4} value={orderAddress} onChange={e=>setOrderAddress(e.target.value)} placeholder="Nama penerima, jalan, kecamatan, kota, kode pos"/></label><p className="ms-hint">Pembayaran masih berupa simulasi. Setelah dikonfirmasi, pesanan langsung masuk ke antrean Print Partner.</p><button className="ms-order-submit" disabled={busy||!variantId||!orderAddress.trim()}><ShoppingCart size={16}/>{busy?"Memproses…":"Konfirmasi & pesan"}</button></form></div>}
 </div>
}
